// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzvjkfgdmtmhsczynqth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6dmprZmdkbXRtaHNjenlucXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODY0NTcsImV4cCI6MjA2NDU2MjQ1N30.eYDYmFpuL3ON86gfXoRciLU2JdHRgwt2zHvK2obAh9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);